-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-08-15 10:38:23 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cenovnik 
    ( 
     cenovnik_id  NUMBER  NOT NULL , 
     iznos        NUMBER (5)  NOT NULL , 
     datum_izmene DATE  NOT NULL , 
     sala_id      NUMBER , 
     usluga_id    NUMBER 
    ) 
;

ALTER TABLE Cenovnik 
    ADD CONSTRAINT Cenovnik_PK PRIMARY KEY ( cenovnik_id ) ;

ALTER TABLE Cenovnik
    ADD CONSTRAINT CK_Cenovnik_Tip
    CHECK (
        (sala_id IS NOT NULL AND usluga_id IS NULL)
        OR
        (sala_id IS NULL AND usluga_id IS NOT NULL)
    );

CREATE TABLE Dekoraterska_firma 
    ( 
     opis      VARCHAR2 (512) , 
     usluga_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Dekoraterska_firma 
    ADD CONSTRAINT Dekoraterska_firma_PK PRIMARY KEY ( usluga_id ) ;

CREATE TABLE Fotograf 
    ( 
     cena_foto NUMBER (4) , 
     usluga_id NUMBER  NOT NULL , 
     tip_foto  VARCHAR2 (25)  NOT NULL 
    ) 
;

ALTER TABLE Fotograf 
    ADD 
    CHECK (tip_foto IN ('FOTOGRAFIJA', 'FOTOGRAFIJA_SNIMANJE')) 
;

ALTER TABLE Fotograf 
    ADD CONSTRAINT Fotograf_PK PRIMARY KEY ( usluga_id ) ;

CREATE TABLE Ketering_firma 
    ( 
     opis      VARCHAR2 (512) , 
     usluga_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Ketering_firma 
    ADD CONSTRAINT Ketering_firma_PK PRIMARY KEY ( usluga_id ) ;

CREATE TABLE Klijent 
    ( 
     korisnik_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Klijent 
    ADD CONSTRAINT Klijent_PK PRIMARY KEY ( korisnik_id ) ;

CREATE TABLE Korisnik 
    ( 
     korisnik_id   NUMBER  NOT NULL , 
     lozinka       VARCHAR2 (128)  NOT NULL , 
     ime           VARCHAR2 (35)  NOT NULL , 
     prezime       VARCHAR2 (35)  NOT NULL , 
     telefon       VARCHAR2 (20) , 
     email         VARCHAR2 (128)  NOT NULL , 
     tip_korisnika VARCHAR2 (20)  , 
     uloga_id      NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Korisnik 
    ADD 
    CHECK (tip_korisnika IN ('KLIJENT', 'RADNIK')) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT Korisnik_PK PRIMARY KEY ( korisnik_id ) ;

CREATE TABLE Muzicki_izvodjac 
    ( 
     tip_muzicara VARCHAR2 (15)  NOT NULL , 
     usluga_id    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Muzicki_izvodjac 
    ADD 
    CHECK (tip_muzicara IN ('BEND', 'DJ', 'TAMBURASI', 'TRUBACI')) 
;

ALTER TABLE Muzicki_izvodjac 
    ADD CONSTRAINT Muzicki_izvodjac_PK PRIMARY KEY ( usluga_id ) ;

CREATE TABLE Paket 
    ( 
     paket_id    NUMBER  NOT NULL , 
     naziv       VARCHAR2 (50)  NOT NULL , 
     opis        VARCHAR2 (512) , 
     status      VARCHAR2 (10)  NOT NULL , 
     restoran_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Paket 
    ADD 
    CHECK (status IN ('AKTIVNO', 'NEAKTIVNO')) 
;

ALTER TABLE Paket 
    ADD CONSTRAINT Paket_PK PRIMARY KEY ( paket_id ) ;

CREATE TABLE Paket_Sala 
    ( 
     sala_id  NUMBER  NOT NULL , 
     paket_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Paket_Sala 
    ADD CONSTRAINT Paket_Sala_PK PRIMARY KEY ( sala_id, paket_id ) ;

CREATE TABLE Paket_Usluga 
    ( 
     paket_id  NUMBER  NOT NULL , 
     usluga_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Paket_Usluga 
    ADD CONSTRAINT Paket_Usluga_PK PRIMARY KEY ( paket_id, usluga_id ) ;

CREATE TABLE Radnik 
    ( 
     korisnik_id NUMBER  NOT NULL , 
     tip_radnika VARCHAR2 (10)  NOT NULL , 
     restoran_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Radnik 
    ADD 
    CHECK (tip_radnika IN ('MENADZER', 'OPERATER')) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_PK PRIMARY KEY ( korisnik_id ) ;

CREATE TABLE Restoran 
    ( 
     restoran_id NUMBER  NOT NULL , 
     telefon     VARCHAR2 (20)  NOT NULL , 
     radno_vreme VARCHAR2 (30) , 
     adresa      VARCHAR2 (40)  NOT NULL , 
     grad        VARCHAR2 (20)  NOT NULL , 
     status      VARCHAR2 (10)  NOT NULL , 
     naziv       VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE Restoran 
    ADD 
    CHECK (status IN ('AKTIVNO', 'NEAKTIVNO')) 
;

ALTER TABLE Restoran 
    ADD CONSTRAINT Restoran_PK PRIMARY KEY ( restoran_id ) ;

CREATE TABLE Rezervacija 
    ( 
     rezervacija_id  NUMBER  NOT NULL , 
     br_gostiju      NUMBER  NOT NULL , 
     opis            VARCHAR2 (512) , 
     napomena        VARCHAR2 (512) , 
     vreme_pocetka   DATE  NOT NULL , 
     vreme_zavrsetka DATE  NOT NULL , 
     vreme_kreiranja DATE  NOT NULL , 
     status_rez      VARCHAR2 (20)  NOT NULL , 
     korisnik_id     NUMBER  NOT NULL , 
     paket_id        NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Rezervacija 
    ADD 
    CHECK (status_rez IN ('ODBIJENA', 'OTKAZANA', 'POSLATA', 'POTVRDJENA', 'REALIZOVANA')) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT Rezervacija_PK PRIMARY KEY ( rezervacija_id ) ;

CREATE TABLE Rezervacija_TipDogadjaja 
    ( 
     tip_dogadjaja_id NUMBER  NOT NULL , 
     rezervacija_id   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Rezervacija_TipDogadjaja 
    ADD CONSTRAINT Rezervacija_TipDogadjaja_PK PRIMARY KEY ( tip_dogadjaja_id, rezervacija_id ) ;

CREATE TABLE Sala 
    ( 
     sala_id     NUMBER  NOT NULL , 
     rbr_s       NUMBER  NOT NULL , 
     kapacitet   NUMBER  NOT NULL , 
     status      VARCHAR2 (10)  NOT NULL , 
     restoran_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Sala 
    ADD 
    CHECK (status IN ('AKTIVNO', 'NEAKTIVNO')) 
;

ALTER TABLE Sala 
    ADD CONSTRAINT Sala_PK PRIMARY KEY ( sala_id ) ;

CREATE TABLE Stavka_rezervacije 
    ( 
     stavka_id      NUMBER  NOT NULL , 
     tip_stavke     VARCHAR2 (20)  NOT NULL , 
     rezervacija_id NUMBER  NOT NULL , 
     usluga_id      NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Stavka_rezervacije 
    ADD 
    CHECK (tip_stavke IN ('DEKORATER', 'FOTOGRAF', 'KETERING', 'MUZICKI_IZVODJAC')) 
;

ALTER TABLE Stavka_rezervacije 
    ADD CONSTRAINT Stavka_rezervacije_PK PRIMARY KEY ( stavka_id, rezervacija_id ) ;

CREATE TABLE Tip_dogadjaja 
    ( 
     tip_dogadjaja_id NUMBER  NOT NULL , 
     tip_dogadjaja    VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE Tip_dogadjaja 
    ADD 
    CHECK (tip_dogadjaja IN ('KRSTENJE', 'POSLOVNI_DOGADJAJ', 'RODJENDAN', 'VENCANJE')) 
;

ALTER TABLE Tip_dogadjaja 
    ADD CONSTRAINT Tip_dogadjaja_PK PRIMARY KEY ( tip_dogadjaja_id ) ;

CREATE TABLE Uloga 
    ( 
     uloga_id  NUMBER  NOT NULL , 
     tip_uloge VARCHAR2 (15)  NOT NULL 
    ) 
;

ALTER TABLE Uloga 
    ADD 
    CHECK (tip_uloge IN ('ADMINISTRATOR', 'KLIJENT', 'MENADZER', 'OPERATER')) 
;

ALTER TABLE Uloga 
    ADD CONSTRAINT Uloga_PK PRIMARY KEY ( uloga_id ) ;

CREATE TABLE Usluga 
    ( 
     status     VARCHAR2 (10)  NOT NULL , 
     usluga_id  NUMBER  NOT NULL , 
     telefon    VARCHAR2 (20)  NOT NULL , 
     tip_usluge VARCHAR2 (20)  NOT NULL , 
     naziv_u    VARCHAR2 (128)  NOT NULL , 
     portfolio  VARCHAR2 (512) 
    ) 
;

ALTER TABLE Usluga 
    ADD 
    CHECK (status IN ('AKTIVNO', 'NEAKTIVNO')) 
;

ALTER TABLE Usluga 
    ADD 
    CHECK (tip_usluge IN ('DEKORATER', 'FOTOGRAF', 'KETERING', 'MUZICKI_IZVODJAC')) 
;

ALTER TABLE Usluga 
    ADD CONSTRAINT Usluga_PK PRIMARY KEY ( usluga_id ) ;

ALTER TABLE Cenovnik 
    ADD CONSTRAINT C_Sala_FK FOREIGN KEY 
    ( 
     sala_id
    ) 
    REFERENCES Sala 
    ( 
     sala_id
    ) 
;

ALTER TABLE Cenovnik 
    ADD CONSTRAINT C_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Dekoraterska_firma 
    ADD CONSTRAINT D_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Fotograf 
    ADD CONSTRAINT F_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Ketering_firma 
    ADD CONSTRAINT K_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Klijent 
    ADD CONSTRAINT Klijent_FK FOREIGN KEY 
    ( 
     korisnik_id
    ) 
    REFERENCES Korisnik 
    ( 
     korisnik_id
    ) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT Korisnik_Uloga_FK FOREIGN KEY 
    ( 
     uloga_id
    ) 
    REFERENCES Uloga 
    ( 
     uloga_id
    ) 
;

ALTER TABLE Muzicki_izvodjac 
    ADD CONSTRAINT M_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Paket 
    ADD CONSTRAINT P_Restoran_FK FOREIGN KEY 
    ( 
     restoran_id
    ) 
    REFERENCES Restoran 
    ( 
     restoran_id
    ) 
;

ALTER TABLE Paket_Sala 
    ADD CONSTRAINT PS_Paket_FK FOREIGN KEY 
    ( 
     paket_id
    ) 
    REFERENCES Paket 
    ( 
     paket_id
    ) 
;

ALTER TABLE Paket_Sala 
    ADD CONSTRAINT PS_Sala_FK FOREIGN KEY 
    ( 
     sala_id
    ) 
    REFERENCES Sala 
    ( 
     sala_id
    ) 
;

ALTER TABLE Paket_Usluga 
    ADD CONSTRAINT PU_Paket_FK FOREIGN KEY 
    ( 
     paket_id
    ) 
    REFERENCES Paket 
    ( 
     paket_id
    ) 
;

ALTER TABLE Paket_Usluga 
    ADD CONSTRAINT PU_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT R_Klijent_FK FOREIGN KEY 
    ( 
     korisnik_id
    ) 
    REFERENCES Klijent 
    ( 
     korisnik_id
    ) 
;

ALTER TABLE Rezervacija 
    ADD CONSTRAINT R_Paket_FK FOREIGN KEY 
    ( 
     paket_id
    ) 
    REFERENCES Paket 
    ( 
     paket_id
    ) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT R_Restoran_FK FOREIGN KEY 
    ( 
     restoran_id
    ) 
    REFERENCES Restoran 
    ( 
     restoran_id
    ) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_FK FOREIGN KEY 
    ( 
     korisnik_id
    ) 
    REFERENCES Korisnik 
    ( 
     korisnik_id
    ) 
;

ALTER TABLE Rezervacija_TipDogadjaja 
    ADD CONSTRAINT RTD_Rezervacija_FK FOREIGN KEY 
    ( 
     rezervacija_id
    ) 
    REFERENCES Rezervacija 
    ( 
     rezervacija_id
    ) 
;

ALTER TABLE Rezervacija_TipDogadjaja 
    ADD CONSTRAINT RTD_Tip_dogadjaja_FK FOREIGN KEY 
    ( 
     tip_dogadjaja_id
    ) 
    REFERENCES Tip_dogadjaja 
    ( 
     tip_dogadjaja_id
    ) 
;

ALTER TABLE Sala 
    ADD CONSTRAINT Sala_Restoran_FK FOREIGN KEY 
    ( 
     restoran_id
    ) 
    REFERENCES Restoran 
    ( 
     restoran_id
    ) 
;

ALTER TABLE Stavka_rezervacije 
    ADD CONSTRAINT Sr_Rezervacija_FK FOREIGN KEY 
    ( 
     rezervacija_id
    ) 
    REFERENCES Rezervacija 
    ( 
     rezervacija_id
    ) 
;

ALTER TABLE Stavka_rezervacije 
    ADD CONSTRAINT Sr_Usluga_FK FOREIGN KEY 
    ( 
     usluga_id
    ) 
    REFERENCES Usluga 
    ( 
     usluga_id
    ) 
;

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Klijent 
BEFORE INSERT OR UPDATE OF korisnik_id 
ON Klijent 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.korisnik_id = :new.korisnik_id; 
    IF (d IS NULL OR d <> 'KLIJENT') THEN 
        raise_application_error(-20223,'FK Klijent_FK in Table Klijent violates Arc constraint on Table Korisnik - discriminator column tip_korisnika doesn''t have value ''KLIJENT'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Radnik 
BEFORE INSERT OR UPDATE OF korisnik_id 
ON Radnik 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_korisnika INTO d 
    FROM Korisnik A 
    WHERE A.korisnik_id = :new.korisnik_id; 
    IF (d IS NULL OR d <> 'RADNIK') THEN 
        raise_application_error(-20223,'FK Radnik_FK in Table Radnik violates Arc constraint on Table Korisnik - discriminator column tip_korisnika doesn''t have value ''RADNIK'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_2_Ketering_firma 
BEFORE INSERT OR UPDATE OF usluga_id 
ON Ketering_firma 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_usluge INTO d 
    FROM Usluga A 
    WHERE A.usluga_id = :new.usluga_id; 
    IF (d IS NULL OR d <> 'KETERING') THEN 
        raise_application_error(-20223,'FK K_Usluga_FK in Table Ketering_firma violates Arc constraint on Table Usluga - discriminator column tip_usluge doesn''t have value ''KETERING'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_2_Muzicki_izvodjac 
BEFORE INSERT OR UPDATE OF usluga_id 
ON Muzicki_izvodjac 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_usluge INTO d 
    FROM Usluga A 
    WHERE A.usluga_id = :new.usluga_id; 
    IF (d IS NULL OR d <> 'MUZICKI_IZVODJAC') THEN 
        raise_application_error(-20223,'FK M_Usluga_FK in Table Muzicki_izvodjac violates Arc constraint on Table Usluga - discriminator column tip_usluge doesn''t have value ''MUZICKI_IZVODJAC'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_2_Dekoraterska_firma 
BEFORE INSERT OR UPDATE OF usluga_id 
ON Dekoraterska_firma 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_usluge INTO d 
    FROM Usluga A 
    WHERE A.usluga_id = :new.usluga_id; 
    IF (d IS NULL OR d <> 'DEKORATER') THEN 
        raise_application_error(-20223,'FK D_Usluga_FK in Table Dekoraterska_firma violates Arc constraint on Table Usluga - discriminator column tip_usluge doesn''t have value ''DEKORATER'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_2_Fotograf 
BEFORE INSERT OR UPDATE OF usluga_id 
ON Fotograf 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (20); 
BEGIN 
    SELECT A.tip_usluge INTO d 
    FROM Usluga A 
    WHERE A.usluga_id = :new.usluga_id; 
    IF (d IS NULL OR d <> 'FOTOGRAF') THEN 
        raise_application_error(-20223,'FK F_Usluga_FK in Table Fotograf violates Arc constraint on Table Usluga - discriminator column tip_usluge doesn''t have value ''FOTOGRAF'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             0
-- ALTER TABLE                             54
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
